version: '3.8'

services:
  hivision_idphotos:
    build:
      context: .
      dockerfile: Dockerfile
    # Use the unified FastAPI server that serves:
    #   - Home pages at /
    #   - Gradio tool at /tool
    #   - API mounted at /api
    # Ensure weights on start, then run the unified server
    command: bash -lc "python -u scripts/ensure_weights.py && python -u serve.py"
    ports:
      - '0.0.0.0:8000:8000'
      - '0.0.0.0:80:8000'
      - '0.0.0.0:7860:7860'
    # Persist or reuse weights to avoid re-downloading across container restarts
    volumes:
      - ./hivision/creator/weights:/app/hivision/creator/weights

  # Standalone API service (optional). The unified server above
  # already mounts the API at /api, but we keep this for compatibility.
  hivision_idphotos_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -lc "python -u scripts/ensure_weights.py && python -u deploy_api.py"
    ports:
      - '8080:8080'
