version: '3.8'

services:
  hivision_idphotos:
    build:
      context: .
      dockerfile: Dockerfile
    # Use the unified FastAPI server that serves:
    #   - Home pages at /
    #   - Gradio tool at /tool
    #   - API mounted at /api
    command: python3 -u serve.py
    ports:
      - '8000:8000'

  # Standalone API service (optional). The unified server above
  # already mounts the API at /api, but we keep this for compatibility.
  hivision_idphotos_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 deploy_api.py
    ports:
      - '8080:8080'
