name: Build Docker image and push to GHCR (with models)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build helpers for model download
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm

      - name: Download models into repo (bundled in image)
        run: |
          python scripts/download_model.py --models all

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image name (lowercase)
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$(echo '${{ github.repository }}' | awk -F'/' '{print tolower($2)}')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Trigger Dokploy redeploy (optional)
        if: ${{ secrets.DOKPLOY_WEBHOOK_URL != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}" || true

